services:
  db:
    image: postgres:17-bookworm
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: redis-server --appendonly yes
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  oj-cpp-runner:
    build:
      context: ./judge-engine/docker-env/cpp
    image: oj-cpp:latest
    deploy:
      replicas: 0

  judge-engine:
    build:
      context: ./judge-engine
      target: build
    container_name: judge-app
    ports:
      - "${JUDGE_PORT}:4000"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      JUDGE_CPP_DOCKERFILE_PATH: /app/judge-engine/docker-env/cpp/
    volumes:
      - ./judge-engine:/app/judge-engine
      - m2:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/byebug/sandbox:/tmp/byebug/sandbox
    command: mvn spring-boot:run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  backend:
    build:
      context: ./backend
      target: build
    container_name: spring-boot-app
    ports:
      - "${SPRING_PORT}:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
    volumes:
      - ./backend:/app/backend
      - m2:/root/.m2
    command: mvn spring-boot:run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "${VITE_PORT}:5173"
    environment:
      VITE_PORT: ${VITE_PORT}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    depends_on:
      oj-cpp-runner:
        condition: service_started
      backend:
        condition: service_healthy
      judge-engine:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

volumes:
  db-data:
  m2:
  redis-data:
