-- 1. Bảng Users
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    gender VARCHAR(10),
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    total_score INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    avatar_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP
);

-- 2. Bảng Tags
CREATE TABLE IF NOT EXISTS tags (
    tag_id SERIAL PRIMARY KEY,
    tag_name VARCHAR(50) NOT NULL UNIQUE
);

-- 3. Bảng Problems (ĐÃ THÊM required_solved)
CREATE TABLE IF NOT EXISTS problems (
    problem_id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    difficulty VARCHAR(20) CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    time_limit_ms INTEGER DEFAULT 1000,
    memory_limit_mb INTEGER DEFAULT 256,
    is_public BOOLEAN DEFAULT TRUE,
    -- Thuộc tính mới: Số bài cần giải để mở khóa bài này
    required_solved INTEGER DEFAULT 0, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT REFERENCES users(user_id)
);

-- 4. Bảng trung gian Problem_Tags
CREATE TABLE IF NOT EXISTS problem_tags (
    problem_id INTEGER REFERENCES problems(problem_id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES tags(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (problem_id, tag_id)
);

-- 5. Bảng Testcases
CREATE TABLE IF NOT EXISTS testcases (
    testcase_id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES problems(problem_id) ON DELETE CASCADE,
    input_path TEXT NOT NULL,
    output_path TEXT NOT NULL,
    is_visible BOOLEAN DEFAULT TRUE,
    score_weight INTEGER DEFAULT 0
);

-- 6. Bảng Submissions
CREATE TABLE IF NOT EXISTS submissions (
    submission_id SERIAL PRIMARY KEY,
    problem_id INTEGER REFERENCES problems(problem_id),
    user_id BIGINT REFERENCES users(user_id),
    language VARCHAR(20),
    source_code TEXT,
    verdict VARCHAR(20),
    score INTEGER,
    total_time_ms INTEGER,
    max_memory_kb INTEGER,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Bảng Testcase_Results
CREATE TABLE IF NOT EXISTS testcase_results (
    result_id SERIAL PRIMARY KEY,
    submission_id INTEGER REFERENCES submissions(submission_id) ON DELETE CASCADE,
    testcase_id INTEGER REFERENCES testcases(testcase_id),
    verdict VARCHAR(20),
    time_ms INTEGER,
    memory_kb INTEGER
);

-- 8. Bảng Notifications
CREATE TABLE IF NOT EXISTS notifications (
    notification_id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id),
    title VARCHAR(255),
    content TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------
-- PHẦN INSERT DỮ LIỆU
---------------------------------------------------------

-- Khởi tạo Users
INSERT INTO users (username, full_name, email, password_hash, gender, role, total_score, is_active) 
VALUES 
('admin123', 'Chủ Trang Web', 'admin123@gmail.com', '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW', 'female', 'ADMIN', 0, true),
('coder_01', 'Người Dùng Mẫu', 'user@example.com', '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW', 'male', 'USER', 150, true);

-- Khởi tạo Tags
INSERT INTO tags (tag_name) VALUES 
('Math'), ('Dynamic Programming'), ('Greedy'), ('String'), 
('Data Structure'), ('Graph'), ('Binary Search'), ('Sorting'), 
('Geometry'), ('Bitmask');

-- Khởi tạo Problems (Thiết lập required_solved cho một số bài khó)
INSERT INTO problems (title, description, difficulty, time_limit_ms, memory_limit_mb, is_public, required_solved, created_by) VALUES
('A + B Problem', 'Tính tổng hai số nguyên a và b.', 'EASY', 1000, 256, true, 0, 1),
('Prime Check', 'Kiểm tra một số có phải số nguyên tố hay không.', 'EASY', 500, 64, true, 0, 1),
('Fibonacci', 'Tìm số Fibonacci thứ n.', 'EASY', 1000, 128, true, 0, 1),
('Longest Common Subsequence', 'Tìm độ dài xâu con chung dài nhất.', 'MEDIUM', 2000, 256, true, 2, 1),
('Dijkstra Algorithm', 'Tìm đường đi ngắn nhất từ 1 đỉnh đến các đỉnh còn lại.', 'MEDIUM', 1500, 256, true, 3, 1),
('Quick Sort Implementation', 'Cài đặt thuật toán sắp xếp nhanh.', 'EASY', 1000, 256, true, 0, 1),
('Knapsack 0/1', 'Bài toán cái túi với các vật phẩm không thể chia cắt.', 'MEDIUM', 1000, 256, true, 5, 1),
('Binary Search Tree Check', 'Kiểm tra một cây có phải cây tìm kiếm nhị phân không.', 'MEDIUM', 1000, 256, true, 5, 1),
('Palindrome String', 'Kiểm tra xâu đối xứng.', 'EASY', 500, 64, true, 0, 1),
('N-Queens Problem', 'Xếp n quân hậu trên bàn cờ n x n.', 'HARD', 3000, 256, true, 10, 1),
('Segment Tree Query', 'Cập nhật và truy vấn tổng đoạn.', 'HARD', 2000, 512, true, 10, 1),
('Convex Hull', 'Tìm bao lồi của một tập điểm trên mặt phẳng.', 'HARD', 2000, 256, true, 15, 1),
('Factorial Large Number', 'Tính giai thừa của một số lớn.', 'EASY', 1000, 128, true, 0, 1),
('Max Flow', 'Tìm luồng cực đại trong mạng tải.', 'HARD', 2000, 256, true, 15, 1),
('BFS Traversal', 'Duyệt đồ thị theo chiều rộng.', 'EASY', 1000, 256, true, 0, 1),
('Merge Intervals', 'Hợp nhất các khoảng giá trị bị chồng lấn.', 'MEDIUM', 1000, 256, true, 5, 1),
('Longest Palindromic Substring', 'Tìm xâu đối xứng dài nhất.', 'MEDIUM', 1500, 256, true, 5, 1),
('Valid Parentheses', 'Kiểm tra tính đúng đắn của các dấu ngoặc.', 'EASY', 500, 64, true, 0, 1),
('Subset Sum', 'Kiểm tra sự tồn tại của tập con có tổng bằng K.', 'MEDIUM', 2000, 256, true, 5, 1),
('Counting Bits', 'Đếm số lượng bit 1 từ 0 đến n.', 'EASY', 500, 64, true, 0, 1);

-- Thiết lập Tags cho bài tập
INSERT INTO problem_tags (problem_id, tag_id)
SELECT p.problem_id, t.tag_id 
FROM problems p, tags t
WHERE 
(p.title = 'A + B Problem' AND t.tag_name = 'Math') OR
(p.title = 'Longest Common Subsequence' AND t.tag_name = 'Dynamic Programming') OR
(p.title = 'Dijkstra Algorithm' AND t.tag_name = 'Graph') OR
(p.title = 'Counting Bits' AND t.tag_name = 'Bitmask') OR
(p.title = 'Palindrome String' AND t.tag_name = 'String');

-- Khởi tạo Testcases cho bài #1
INSERT INTO testcases (problem_id, input_path, output_path, is_visible, score_weight)
VALUES 
(1, 'tc/1/in_1.txt', 'tc/1/out_1.txt', true, 50),
(1, 'tc/1/in_2.txt', 'tc/1/out_2.txt', false, 50);

-- Dữ liệu mẫu nộp bài
INSERT INTO submissions (problem_id, user_id, language, source_code, verdict, score, total_time_ms, max_memory_kb)
VALUES 
(1, 2, 'C++', '#include <iostream>...', 'AC', 100, 15, 1024),
(4, 2, 'Python', 'def lcs(a, b):...', 'WA', 0, 450, 8192);

-- Kết quả chi tiết testcase
INSERT INTO testcase_results (submission_id, testcase_id, verdict, time_ms, memory_kb)
VALUES 
(1, 1, 'AC', 5, 512),
(1, 2, 'AC', 10, 512);

-- Thông báo mẫu
INSERT INTO notifications (user_id, title, content)
VALUES 
(2, 'Kết quả chấm bài', 'Bài nộp A + B Problem của bạn đã đạt 100 điểm.'),
(2, 'Nhắc nhở', 'Đừng quên hoàn thành thử thách hàng ngày nhé!');

-- Đồng bộ hóa lại các sequences để tránh lỗi duplicate key khi insert bằng tay sau này
SELECT setval(pg_get_serial_sequence('problems', 'problem_id'), coalesce(max(problem_id), 1)) FROM problems;
SELECT setval(pg_get_serial_sequence('tags', 'tag_id'), coalesce(max(tag_id), 1)) FROM tags;
SELECT setval(pg_get_serial_sequence('submissions', 'submission_id'), coalesce(max(submission_id), 1)) FROM submissions;