CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    gender VARCHAR(10),
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    total_score INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    avatar_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
    admin_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url    TEXT,
    is_active     BOOLEAN DEFAULT TRUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tags (
    tag_id SERIAL PRIMARY KEY,
    tag_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS problems (
    problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    difficulty VARCHAR(10) NOT NULL,
    time_limit_ms INTEGER DEFAULT 2000,
    memory_limit_kb INTEGER DEFAULT 262144,
    allow_file_submit BOOLEAN DEFAULT FALSE,
    is_public BOOLEAN DEFAULT FALSE,
    created_by BIGINT REFERENCES users(user_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS problem_tags (
    problem_id BIGINT REFERENCES problems(problem_id),
    tag_id INTEGER REFERENCES tags(tag_id),
    PRIMARY KEY (problem_id, tag_id)
);

CREATE TABLE IF NOT EXISTS testcases (
    testcase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL REFERENCES problems(problem_id),
    input_path TEXT NOT NULL,
    output_path TEXT NOT NULL,
    is_visible BOOLEAN DEFAULT FALSE,
    display_order INTEGER DEFAULT 0,
    score_weight INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS submissions (
    submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL REFERENCES problems(problem_id),
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    language VARCHAR(20) NOT NULL,
    source_code TEXT,
    file_url TEXT,
    verdict VARCHAR(10) NOT NULL,
    compile_error TEXT,
    judge_message TEXT,
    score INTEGER DEFAULT 0,
    total_time_ms INTEGER,
    max_memory_kb INTEGER,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testcase_results (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES submissions(submission_id),
    testcase_id BIGINT NOT NULL REFERENCES testcases(testcase_id),
    verdict VARCHAR(10) NOT NULL,
    time_ms INTEGER,
    memory_kb INTEGER
);

CREATE TABLE IF NOT EXISTS notification_broadcasts (
    broadcast_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(200) NOT NULL,
    content             TEXT NOT NULL,
    audience_type       VARCHAR(10)  NOT NULL,
    priority            VARCHAR(10)  NOT NULL DEFAULT 'NORMAL',
    created_by_admin_id BIGINT NOT NULL REFERENCES admins(admin_id),
    scheduled_at        TIMESTAMP,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broadcast_id    BIGINT NOT NULL REFERENCES notification_broadcasts(broadcast_id),
    user_id         BIGINT NOT NULL REFERENCES users(user_id),
    is_read         BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_notifications (
    admin_notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broadcast_id          BIGINT NOT NULL REFERENCES notification_broadcasts(broadcast_id),
    admin_id              BIGINT NOT NULL REFERENCES admins(admin_id),
    is_read               BOOLEAN DEFAULT FALSE,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- tkhoan admin (tách riêng khỏi bảng users)
INSERT INTO admins (username, full_name, email, password_hash, is_active)
VALUES (
    'admin123',
    'Chủ Trang Web',
    'admin123@gmail.com',
    '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
    true
)
ON CONFLICT (username) DO UPDATE SET
    full_name     = EXCLUDED.full_name,
    email         = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    is_active     = true;

-- tkhoan user
INSERT INTO users (username, full_name, email, password_hash, gender, role, total_score, is_active) 
VALUES (
    'coder_01', 
    'Người Dùng Mẫu', 
    'user@example.com', 
    '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW', 
    'male', 
    'USER', -- Cột role mới thêm
    150, 
    true
)
ON CONFLICT (username) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    gender = EXCLUDED.gender,
    role = 'USER',
    total_score = EXCLUDED.total_score,
    is_active = EXCLUDED.is_active,
    deleted_at = NULL;

-- demo users for UserManagement and leaderboard testing
INSERT INTO users (username, full_name, email, password_hash, gender, role, total_score, is_active)
VALUES
    (
        'algo_ace',
        'Algo Ace',
        'algo.ace@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'male',
        'USER',
        2450,
        true
    ),
    (
        'dp_master',
        'DP Master',
        'dp.master@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'female',
        'USER',
        1980,
        true
    ),
    (
        'bug_hunter',
        'Bug Hunter',
        'bug.hunter@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'male',
        'USER',
        1720,
        true
    ),
    (
        'graph_guru',
        'Graph Guru',
        'graph.guru@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'female',
        'USER',
        1360,
        true
    ),
    (
        'binary_wizard',
        'Binary Wizard',
        'binary.wizard@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'male',
        'USER',
        980,
        true
    ),
    (
        'newbie_dev',
        'Newbie Dev',
        'newbie.dev@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'female',
        'USER',
        120,
        true
    ),
    (
        'sleepy_coder',
        'Sleepy Coder',
        'sleepy.coder@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'male',
        'USER',
        420,
        false
    ),
    (
        'rule_breaker',
        'Rule Breaker',
        'rule.breaker@example.com',
        '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW',
        'female',
        'USER',
        35,
        false
    )
ON CONFLICT (username) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    gender = EXCLUDED.gender,
    role = 'USER',
    total_score = EXCLUDED.total_score,
    is_active = EXCLUDED.is_active,
    deleted_at = NULL;

INSERT INTO tags (tag_name) VALUES 
('Math'), ('Dynamic Programming'), ('Greedy'), ('String'), 
('Data Structure'), ('Graph'), ('Binary Search'), ('Sorting'), 
('Geometry'), ('Bitmask');

INSERT INTO problems (
  title,
  description,
  difficulty,
  time_limit_ms,
  memory_limit_kb,
  is_public,
  created_by
) VALUES
(
  'A + B Problem',
  $md$## Mô tả

Cho hai số nguyên $a$ và $b$.

Hãy tính tổng:

$$
a + b
$$

### Yêu cầu

In ra tổng của hai số nguyên đã cho.$md$,
  'EASY',
  1000,
  262144,
  true,
  1
),
(
  'Prime Check',
  $md$## Mô tả

Cho một số nguyên dương $n$.

Hãy kiểm tra xem $n$ có phải là **số nguyên tố** hay không.

Một số nguyên tố là số lớn hơn $1$ và chỉ có đúng hai ước dương là $1$ và chính nó.

### Yêu cầu

In ra kết quả kiểm tra tính nguyên tố của $n$.$md$,
  'EASY',
  500,
  65536,
  true,
  1
),
(
  'Fibonacci',
  $md$## Mô tả

Cho số nguyên không âm $n$.

Hãy tìm số Fibonacci thứ $n$.

Dãy Fibonacci được định nghĩa như sau:

$$
F_0 = 0, \quad F_1 = 1
$$

và với $n \ge 2$:

$$
F_n = F_{n-1} + F_{n-2}
$$

### Yêu cầu

In ra giá trị $F_n$.$md$,
  'EASY',
  1000,
  131072,
  true,
  1
),
(
  'Longest Common Subsequence',
  $md$## Mô tả

Cho hai xâu ký tự $s$ và $t$.

Hãy tìm độ dài của **xâu con chung dài nhất** giữa hai xâu.

Một xâu con không nhất thiết phải liên tiếp, nhưng phải giữ nguyên thứ tự các ký tự.

### Yêu cầu

In ra độ dài LCS của hai xâu.$md$,
  'MEDIUM',
  2000,
  262144,
  true,
  1
),
(
  'Dijkstra Algorithm',
  $md$## Mô tả

Cho một đồ thị có trọng số không âm gồm $n$ đỉnh và $m$ cạnh.

Hãy tìm đường đi ngắn nhất từ một đỉnh nguồn đến các đỉnh còn lại bằng thuật toán Dijkstra.

### Yêu cầu

Với mỗi đỉnh, in ra khoảng cách ngắn nhất từ đỉnh nguồn đến đỉnh đó.$md$,
  'MEDIUM',
  1500,
  262144,
  true,
  1
),
(
  'Quick Sort Implementation',
  $md$## Mô tả

Cho một mảng gồm $n$ số nguyên.

Hãy sắp xếp mảng theo thứ tự không giảm bằng thuật toán **Quick Sort**.

### Yêu cầu

In ra mảng sau khi đã được sắp xếp.$md$,
  'EASY',
  1000,
  262144,
  true,
  1
),
(
  'Knapsack 0/1',
  $md$## Mô tả

Cho $n$ vật phẩm, mỗi vật phẩm có trọng lượng $w_i$ và giá trị $v_i$.

Bạn có một chiếc túi có sức chứa tối đa $W$.

Mỗi vật phẩm chỉ có thể được chọn hoặc không chọn, không thể chia nhỏ.

### Yêu cầu

Tìm tổng giá trị lớn nhất có thể đạt được sao cho tổng trọng lượng không vượt quá $W$.$md$,
  'MEDIUM',
  1000,
  262144,
  true,
  1
),
(
  'Binary Search Tree Check',
  $md$## Mô tả

Cho một cây nhị phân.

Hãy kiểm tra xem cây đó có phải là **cây tìm kiếm nhị phân** hay không.

Với cây tìm kiếm nhị phân, mọi nút trong cây con trái phải nhỏ hơn nút hiện tại, và mọi nút trong cây con phải phải lớn hơn nút hiện tại.

### Yêu cầu

In ra kết quả kiểm tra cây có phải BST hay không.$md$,
  'MEDIUM',
  1000,
  262144,
  true,
  1
),
(
  'Palindrome String',
  $md$## Mô tả

Cho một xâu ký tự $s$.

Hãy kiểm tra xem $s$ có phải là **xâu đối xứng** hay không.

Một xâu được gọi là đối xứng nếu đọc từ trái sang phải giống như đọc từ phải sang trái.

### Yêu cầu

In ra kết quả kiểm tra xâu đối xứng.$md$,
  'EASY',
  500,
  65536,
  true,
  1
),
(
  'N-Queens Problem',
  $md$## Mô tả

Cho bàn cờ kích thước $n \times n$.

Hãy đặt $n$ quân hậu lên bàn cờ sao cho không có hai quân hậu nào tấn công nhau.

Hai quân hậu tấn công nhau nếu chúng nằm cùng hàng, cùng cột hoặc cùng đường chéo.

### Yêu cầu

Tìm một hoặc tất cả cách đặt $n$ quân hậu hợp lệ.$md$,
  'HARD',
  3000,
  262144,
  true,
  1
),
(
  'Segment Tree Query',
  $md$## Mô tả

Cho một mảng gồm $n$ số nguyên.

Cần xử lý hai loại truy vấn:

- Cập nhật giá trị tại một vị trí.
- Tính tổng các phần tử trên đoạn $[l, r]$.

### Yêu cầu

Sử dụng Segment Tree để xử lý các truy vấn hiệu quả.$md$,
  'HARD',
  2000,
  524288,
  true,
  1
),
(
  'Convex Hull',
  $md$## Mô tả

Cho một tập gồm $n$ điểm trên mặt phẳng tọa độ.

Hãy tìm **bao lồi** của tập điểm đó.

Bao lồi là đa giác lồi nhỏ nhất chứa tất cả các điểm đã cho.

### Yêu cầu

In ra các điểm thuộc bao lồi theo thứ tự phù hợp.$md$,
  'HARD',
  2000,
  262144,
  true,
  1
),
(
  'Factorial Large Number',
  $md$## Mô tả

Cho số nguyên không âm $n$.

Hãy tính giai thừa của $n$:

$$
n! = 1 \times 2 \times 3 \times \cdots \times n
$$

Với quy ước:

$$
0! = 1
$$

### Yêu cầu

In ra giá trị $n!$. Kết quả có thể rất lớn.$md$,
  'EASY',
  1000,
  131072,
  true,
  1
),
(
  'Max Flow',
  $md$## Mô tả

Cho một mạng luồng gồm các đỉnh, các cạnh có sức chứa và hai đỉnh đặc biệt là nguồn $s$ và đích $t$.

Hãy tìm luồng cực đại từ $s$ đến $t$.

### Yêu cầu

In ra giá trị luồng cực đại của mạng.$md$,
  'HARD',
  2000,
  262144,
  true,
  1
),
(
  'BFS Traversal',
  $md$## Mô tả

Cho một đồ thị gồm $n$ đỉnh và $m$ cạnh.

Hãy duyệt đồ thị theo chiều rộng bắt đầu từ một đỉnh cho trước.

### Yêu cầu

In ra thứ tự các đỉnh được thăm bằng thuật toán BFS.$md$,
  'EASY',
  1000,
  262144,
  true,
  1
),
(
  'Merge Intervals',
  $md$## Mô tả

Cho danh sách các khoảng $[l_i, r_i]$.

Hãy hợp nhất các khoảng bị chồng lấn với nhau.

Hai khoảng được xem là chồng lấn nếu chúng có phần giao nhau không rỗng.

### Yêu cầu

In ra danh sách các khoảng sau khi đã hợp nhất.$md$,
  'MEDIUM',
  1000,
  262144,
  true,
  1
),
(
  'Longest Palindromic Substring',
  $md$## Mô tả

Cho một xâu ký tự $s$.

Hãy tìm xâu con liên tiếp dài nhất của $s$ là xâu đối xứng.

### Yêu cầu

In ra độ dài hoặc nội dung xâu đối xứng dài nhất.$md$,
  'MEDIUM',
  1500,
  262144,
  true,
  1
),
(
  'Valid Parentheses',
  $md$## Mô tả

Cho một xâu chỉ gồm các ký tự ngoặc:

- `(`
- `)`
- `[`
- `]`
- `{`
- `}`

Hãy kiểm tra xem xâu ngoặc có hợp lệ hay không.

Một xâu ngoặc hợp lệ nếu các dấu ngoặc được đóng đúng thứ tự.

### Yêu cầu

In ra kết quả kiểm tra tính hợp lệ của xâu.$md$,
  'EASY',
  500,
  65536,
  true,
  1
),
(
  'Subset Sum',
  $md$## Mô tả

Cho một mảng gồm $n$ số nguyên và một số nguyên $K$.

Hãy kiểm tra xem có tồn tại một tập con của mảng có tổng bằng $K$ hay không.

### Yêu cầu

In ra kết quả kiểm tra sự tồn tại của tập con thỏa mãn:

$$
\sum a_i = K
$$$md$,
  'MEDIUM',
  2000,
  262144,
  true,
  1
),
(
  'Counting Bits',
  $md$## Mô tả

Cho số nguyên không âm $n$.

Với mỗi số nguyên $i$ thỏa mãn $0 \le i \le n$, hãy đếm số lượng bit `1` trong biểu diễn nhị phân của $i$.

### Yêu cầu

In ra mảng kết quả, trong đó phần tử thứ $i$ là số bit `1` của số $i$.$md$,
  'EASY',
  500,
  65536,
  true,
  1
);

INSERT INTO problem_tags (problem_id, tag_id)
SELECT p.problem_id, t.tag_id 
FROM problems p, tags t
WHERE 
(p.title = 'A + B Problem' AND t.tag_name = 'Math') OR
(p.title = 'Longest Common Subsequence' AND t.tag_name = 'Dynamic Programming') OR
(p.title = 'Dijkstra Algorithm' AND t.tag_name = 'Graph') OR
(p.title = 'Counting Bits' AND t.tag_name = 'Bitmask') OR
(p.title = 'Palindrome String' AND t.tag_name = 'String');

INSERT INTO submissions (problem_id, user_id, language, source_code, verdict, score, total_time_ms, max_memory_kb)
VALUES 
(1, 2, 'CPP', '#include <iostream>...', 'AC', 100, 15, 1024),
(4, 2, 'PYTHON', 'def lcs(a, b):...', 'WA', 0, 450, 8192);


-- Seed notification broadcast + user inbox
INSERT INTO notification_broadcasts (title, content, audience_type, priority, created_by_admin_id)
VALUES (
    'Chào mừng đến với ByeBug!',
    'Hệ thống ByeBug Online Judge đã sẵn sàng. Hãy bắt đầu luyện tập ngay!',
    'ALL',
    'NORMAL',
    1
);

INSERT INTO notifications (broadcast_id, user_id)
SELECT 1, user_id FROM users WHERE deleted_at IS NULL;


SELECT setval(pg_get_serial_sequence('problems', 'problem_id'), coalesce(max(problem_id), 1)) FROM problems;
SELECT setval(pg_get_serial_sequence('tags', 'tag_id'), coalesce(max(tag_id), 1)) FROM tags;
SELECT setval(pg_get_serial_sequence('submissions', 'submission_id'), coalesce(max(submission_id), 1)) FROM submissions;


-- ============================================================
-- Bổ sung dữ liệu còn thiếu: constraints và 2 ví dụ cho mỗi bài
-- Giữ nguyên toàn bộ nội dung phía trên; chỉ thêm phần này ở cuối file
-- ============================================================

ALTER TABLE problems ADD COLUMN IF NOT EXISTS constraints TEXT;

CREATE TABLE IF NOT EXISTS problem_examples (
    example_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL REFERENCES problems(problem_id),
    input TEXT NOT NULL,
    output TEXT NOT NULL,
    explanation TEXT,
    display_order INTEGER DEFAULT 0
);

UPDATE problems
SET constraints = $c1$## Ràng buộc

- $-10^9 \le a, b \le 10^9$
- Dữ liệu vào luôn gồm đúng hai số nguyên.
- Kết quả nằm trong phạm vi kiểu số nguyên 64-bit.$c1$
WHERE title = 'A + B Problem';

UPDATE problems
SET constraints = $c2$## Ràng buộc

- $1 \le n \le 10^9$
- Chỉ có một số nguyên $n$ trên input.
- In `YES` nếu $n$ là số nguyên tố, ngược lại in `NO`.$c2$
WHERE title = 'Prime Check';

UPDATE problems
SET constraints = $c3$## Ràng buộc

- $0 \le n \le 45$
- Kết quả $F_n$ nằm trong phạm vi kiểu số nguyên 32-bit.
- Input gồm đúng một số nguyên không âm $n$.$c3$
WHERE title = 'Fibonacci';

UPDATE problems
SET constraints = $c4$## Ràng buộc

- $1 \le |s|, |t| \le 1000$
- Hai xâu chỉ gồm chữ cái tiếng Anh thường `a` đến `z`.
- Cần in ra một số nguyên là độ dài LCS.$c4$
WHERE title = 'Longest Common Subsequence';

UPDATE problems
SET constraints = $c5$## Ràng buộc

- $1 \le n \le 10^5$
- $0 \le m \le 2 \times 10^5$
- $1 \le u, v, s \le n$
- $0 \le w \le 10^9$
- Nếu một đỉnh không thể đi tới từ $s$, in `-1` cho đỉnh đó.$c5$
WHERE title = 'Dijkstra Algorithm';

UPDATE problems
SET constraints = $c6$## Ràng buộc

- $1 \le n \le 10^5$
- $-10^9 \le a_i \le 10^9$
- Cần in các phần tử sau khi sắp xếp theo thứ tự không giảm.$c6$
WHERE title = 'Quick Sort Implementation';

UPDATE problems
SET constraints = $c7$## Ràng buộc

- $1 \le n \le 100$
- $1 \le W \le 10^4$
- $1 \le w_i \le W$
- $1 \le v_i \le 10^9$
- Mỗi vật phẩm chỉ được chọn tối đa một lần.$c7$
WHERE title = 'Knapsack 0/1';

UPDATE problems
SET constraints = $c8$## Ràng buộc

- $0 \le n \le 10^5$
- Giá trị mỗi nút thỏa mãn $-10^9 \le value \le 10^9$
- Input biểu diễn cây theo level-order, dùng `null` cho nút rỗng.
- In `YES` nếu cây là BST, ngược lại in `NO`.$c8$
WHERE title = 'Binary Search Tree Check';

UPDATE problems
SET constraints = $c9$## Ràng buộc

- $1 \le |s| \le 10^6$
- Xâu $s$ chỉ gồm chữ cái tiếng Anh thường.
- Phân biệt chữ hoa và chữ thường nếu input có chứa chúng.$c9$
WHERE title = 'Palindrome String';

UPDATE problems
SET constraints = $c10$## Ràng buộc

- $1 \le n \le 12$
- Cần in ra số lượng cách đặt $n$ quân hậu hợp lệ.
- Hai cách đặt khác nhau nếu tồn tại ít nhất một hàng có vị trí cột của quân hậu khác nhau.$c10$
WHERE title = 'N-Queens Problem';

UPDATE problems
SET constraints = $c11$## Ràng buộc

- $1 \le n, q \le 2 \times 10^5$
- $-10^9 \le a_i, x \le 10^9$
- Truy vấn dạng `1 i x` cập nhật $a_i = x$.
- Truy vấn dạng `2 l r` yêu cầu in tổng đoạn $[l, r]$.
- Chỉ số trong input được đánh số từ $1$.$c11$
WHERE title = 'Segment Tree Query';

UPDATE problems
SET constraints = $c12$## Ràng buộc

- $1 \le n \le 2 \times 10^5$
- $-10^9 \le x_i, y_i \le 10^9$
- Không có hai điểm nào hoàn toàn giống nhau.
- In số lượng điểm trên bao lồi, sau đó in các điểm theo thứ tự ngược hoặc thuận chiều kim đồng hồ.$c12$
WHERE title = 'Convex Hull';

UPDATE problems
SET constraints = $c13$## Ràng buộc

- $0 \le n \le 500$
- Kết quả có thể vượt quá kiểu số nguyên 64-bit.
- Cần in chính xác toàn bộ giá trị của $n!$.$c13$
WHERE title = 'Factorial Large Number';

UPDATE problems
SET constraints = $c14$## Ràng buộc

- $2 \le n \le 500$
- $0 \le m \le 5000$
- $1 \le s, t \le n$ và $s 
e t$
- $0 \le c_i \le 10^9$
- Các cạnh có hướng. Nếu có nhiều cạnh cùng cặp đỉnh, xem như các cạnh độc lập.$c14$
WHERE title = 'Max Flow';

UPDATE problems
SET constraints = $c15$## Ràng buộc

- $1 \le n \le 10^5$
- $0 \le m \le 2 \times 10^5$
- $1 \le u, v, s \le n$
- Đồ thị vô hướng.
- Khi có nhiều đỉnh kề chưa thăm, duyệt theo thứ tự tăng dần chỉ số đỉnh.$c15$
WHERE title = 'BFS Traversal';

UPDATE problems
SET constraints = $c16$## Ràng buộc

- $1 \le n \le 10^5$
- $-10^9 \le l_i \le r_i \le 10^9$
- Hai khoảng $[l_1,r_1]$ và $[l_2,r_2]$ được gộp nếu chúng giao nhau hoặc chạm nhau.
- In các khoảng sau khi gộp theo thứ tự tăng dần của đầu trái.$c16$
WHERE title = 'Merge Intervals';

UPDATE problems
SET constraints = $c17$## Ràng buộc

- $1 \le |s| \le 5000$
- Xâu $s$ chỉ gồm chữ cái tiếng Anh thường.
- Nếu có nhiều xâu con đối xứng dài nhất, có thể in ra bất kỳ một xâu hợp lệ.$c17$
WHERE title = 'Longest Palindromic Substring';

UPDATE problems
SET constraints = $c18$## Ràng buộc

- $1 \le |s| \le 10^6$
- Xâu $s$ chỉ gồm các ký tự `(`, `)`, `[`, `]`, `{`, `}`.
- In `YES` nếu xâu ngoặc hợp lệ, ngược lại in `NO`.$c18$
WHERE title = 'Valid Parentheses';

UPDATE problems
SET constraints = $c19$## Ràng buộc

- $1 \le n \le 200$
- $0 \le K \le 10^5$
- $0 \le a_i \le 10^5$
- Cần in `YES` nếu tồn tại một tập con có tổng bằng $K$, ngược lại in `NO`.$c19$
WHERE title = 'Subset Sum';

UPDATE problems
SET constraints = $c20$## Ràng buộc

- $0 \le n \le 10^5$
- Cần in $n + 1$ số nguyên.
- Số thứ $i$ trong output là số lượng bit `1` trong biểu diễn nhị phân của $i$.$c20$
WHERE title = 'Counting Bits';


-- Thêm đúng 2 sample cho mỗi bài. Các ví dụ được insert theo title để không phụ thuộc problem_id.

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i1_1$2 3$i1_1$, $o1_1$5$o1_1$, $e1_1$Ta có $a = 2$, $b = 3$. Vì vậy $a + b = 5$.$e1_1$, 1
FROM problems p
WHERE p.title = 'A + B Problem'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i1_2$10 -4$i1_2$, $o1_2$6$o1_2$, $e1_2$Ta có $a = 10$, $b = -4$. Vì vậy $a + b = 6$.$e1_2$, 2
FROM problems p
WHERE p.title = 'A + B Problem'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i2_1$7$i2_1$, $o2_1$YES$o2_1$, $e2_1$Số $7$ chỉ có hai ước dương là $1$ và $7$, nên $7$ là số nguyên tố.$e2_1$, 1
FROM problems p
WHERE p.title = 'Prime Check'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i2_2$12$i2_2$, $o2_2$NO$o2_2$, $e2_2$Số $12$ chia hết cho $2$, nên $12$ không phải là số nguyên tố.$e2_2$, 2
FROM problems p
WHERE p.title = 'Prime Check'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i3_1$5$i3_1$, $o3_1$5$o3_1$, $e3_1$Dãy Fibonacci bắt đầu là $0, 1, 1, 2, 3, 5$, nên $F_5 = 5$.$e3_1$, 1
FROM problems p
WHERE p.title = 'Fibonacci'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i3_2$10$i3_2$, $o3_2$55$o3_2$, $e3_2$Theo công thức truy hồi, $F_{10} = 55$.$e3_2$, 2
FROM problems p
WHERE p.title = 'Fibonacci'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i4_1$abcde
ace$i4_1$, $o4_1$3$o4_1$, $e4_1$Một xâu con chung dài nhất là `ace`, có độ dài $3$.$e4_1$, 1
FROM problems p
WHERE p.title = 'Longest Common Subsequence'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i4_2$abc
def$i4_2$, $o4_2$0$o4_2$, $e4_2$Hai xâu không có ký tự chung nào, nên độ dài LCS bằng $0$.$e4_2$, 2
FROM problems p
WHERE p.title = 'Longest Common Subsequence'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i5_1$4 4 1
1 2 5
1 3 2
3 2 1
2 4 3$i5_1$, $o5_1$0 3 2 6$o5_1$, $e5_1$Từ đỉnh $1$, khoảng cách ngắn nhất đến các đỉnh lần lượt là $0, 3, 2, 6$.$e5_1$, 1
FROM problems p
WHERE p.title = 'Dijkstra Algorithm'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i5_2$3 1 2
1 3 7$i5_2$, $o5_2$-1 0 -1$o5_2$, $e5_2$Bắt đầu từ đỉnh $2$, không thể đi tới đỉnh $1$ và $3$.$e5_2$, 2
FROM problems p
WHERE p.title = 'Dijkstra Algorithm'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i6_1$5
5 1 4 2 3$i6_1$, $o6_1$1 2 3 4 5$o6_1$, $e6_1$Sau khi sắp xếp mảng $[5,1,4,2,3]$, ta được $[1,2,3,4,5]$.$e6_1$, 1
FROM problems p
WHERE p.title = 'Quick Sort Implementation'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i6_2$6
3 3 -1 0 2 -1$i6_2$, $o6_2$-1 -1 0 2 3 3$o6_2$, $e6_2$Các phần tử âm, dương và trùng nhau đều được sắp xếp theo thứ tự không giảm.$e6_2$, 2
FROM problems p
WHERE p.title = 'Quick Sort Implementation'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i7_1$3 5
2 3
3 4
4 5$i7_1$, $o7_1$7$o7_1$, $e7_1$Chọn vật phẩm $1$ và $2$ có tổng trọng lượng $2 + 3 = 5$ và tổng giá trị $3 + 4 = 7$.$e7_1$, 1
FROM problems p
WHERE p.title = 'Knapsack 0/1'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i7_2$4 7
6 13
4 8
3 6
5 12$i7_2$, $o7_2$14$o7_2$, $e7_2$Chọn vật phẩm có trọng lượng $4$ và $3$, tổng giá trị là $8 + 6 = 14$.$e7_2$, 2
FROM problems p
WHERE p.title = 'Knapsack 0/1'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i8_1$3
2 1 3$i8_1$, $o8_1$YES$o8_1$, $e8_1$Nút trái $1 < 2$ và nút phải $3 > 2$, nên cây là BST.$e8_1$, 1
FROM problems p
WHERE p.title = 'Binary Search Tree Check'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i8_2$3
5 1 4 null null 3 6$i8_2$, $o8_2$NO$o8_2$, $e8_2$Nút $3$ nằm trong cây con phải của $5$ nhưng $3 < 5$, nên vi phạm điều kiện BST.$e8_2$, 2
FROM problems p
WHERE p.title = 'Binary Search Tree Check'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i9_1$radar$i9_1$, $o9_1$YES$o9_1$, $e9_1$Xâu `radar` đọc từ trái sang phải và từ phải sang trái đều giống nhau.$e9_1$, 1
FROM problems p
WHERE p.title = 'Palindrome String'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i9_2$hello$i9_2$, $o9_2$NO$o9_2$, $e9_2$Xâu `hello` khi đảo ngược thành `olleh`, khác xâu ban đầu.$e9_2$, 2
FROM problems p
WHERE p.title = 'Palindrome String'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i10_1$4$i10_1$, $o10_1$2$o10_1$, $e10_1$Với bàn cờ $4 \times 4$, có đúng $2$ cách đặt $4$ quân hậu không tấn công nhau.$e10_1$, 1
FROM problems p
WHERE p.title = 'N-Queens Problem'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i10_2$1$i10_2$, $o10_2$1$o10_2$, $e10_2$Với $n = 1$, chỉ có một ô nên có đúng $1$ cách đặt.$e10_2$, 2
FROM problems p
WHERE p.title = 'N-Queens Problem'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i11_1$5 3
1 2 3 4 5
2 1 3
1 2 10
2 1 3$i11_1$, $o11_1$6
14$o11_1$, $e11_1$Tổng đoạn $[1,3]$ ban đầu là $1+2+3=6$. Sau khi cập nhật $a_2=10$, tổng là $1+10+3=14$.$e11_1$, 1
FROM problems p
WHERE p.title = 'Segment Tree Query'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i11_2$4 2
5 5 5 5
2 2 4
1 4 1$i11_2$, $o11_2$15$o11_2$, $e11_2$Truy vấn đầu tiên lấy tổng $a_2+a_3+a_4=15$. Truy vấn cập nhật không cần in kết quả.$e11_2$, 2
FROM problems p
WHERE p.title = 'Segment Tree Query'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i12_1$4
0 0
0 1
1 0
1 1$i12_1$, $o12_1$4
0 0
1 0
1 1
0 1$o12_1$, $e12_1$Bốn điểm tạo thành một hình vuông, tất cả đều nằm trên bao lồi.$e12_1$, 1
FROM problems p
WHERE p.title = 'Convex Hull'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i12_2$5
0 0
2 0
2 2
0 2
1 1$i12_2$, $o12_2$4
0 0
2 0
2 2
0 2$o12_2$, $e12_2$Điểm $(1,1)$ nằm bên trong hình vuông nên không thuộc bao lồi.$e12_2$, 2
FROM problems p
WHERE p.title = 'Convex Hull'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i13_1$5$i13_1$, $o13_1$120$o13_1$, $e13_1$Ta có $5! = 1 \times 2 \times 3 \times 4 \times 5 = 120$.$e13_1$, 1
FROM problems p
WHERE p.title = 'Factorial Large Number'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i13_2$0$i13_2$, $o13_2$1$o13_2$, $e13_2$Theo quy ước, $0! = 1$.$e13_2$, 2
FROM problems p
WHERE p.title = 'Factorial Large Number'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i14_1$4 5 1 4
1 2 3
1 3 2
2 3 1
2 4 2
3 4 4$i14_1$, $o14_1$5$o14_1$, $e14_1$Có thể đẩy tổng luồng cực đại $5$ từ nguồn $1$ đến đích $4$.$e14_1$, 1
FROM problems p
WHERE p.title = 'Max Flow'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i14_2$3 2 1 3
1 2 10
2 3 4$i14_2$, $o14_2$4$o14_2$, $e14_2$Cạnh $2 \to 3$ có sức chứa $4$, nên luồng cực đại không thể vượt quá $4$.$e14_2$, 2
FROM problems p
WHERE p.title = 'Max Flow'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i15_1$5 4 1
1 2
1 3
2 4
3 5$i15_1$, $o15_1$1 2 3 4 5$o15_1$, $e15_1$BFS bắt đầu từ $1$, sau đó thăm $2,3$, rồi lần lượt thăm $4,5$.$e15_1$, 1
FROM problems p
WHERE p.title = 'BFS Traversal'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i15_2$4 2 3
1 2
3 4$i15_2$, $o15_2$3 4$o15_2$, $e15_2$Từ đỉnh $3$ chỉ đi được đến đỉnh $4$, nên thứ tự duyệt là `3 4`.$e15_2$, 2
FROM problems p
WHERE p.title = 'BFS Traversal'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i16_1$4
1 3
2 6
8 10
15 18$i16_1$, $o16_1$3
1 6
8 10
15 18$o16_1$, $e16_1$Hai khoảng $[1,3]$ và $[2,6]$ chồng lấn nên được gộp thành $[1,6]$.$e16_1$, 1
FROM problems p
WHERE p.title = 'Merge Intervals'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i16_2$3
1 4
4 5
10 12$i16_2$, $o16_2$2
1 5
10 12$o16_2$, $e16_2$Hai khoảng $[1,4]$ và $[4,5]$ chạm nhau tại $4$, nên được gộp thành $[1,5]$.$e16_2$, 2
FROM problems p
WHERE p.title = 'Merge Intervals'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i17_1$babad$i17_1$, $o17_1$bab$o17_1$, $e17_1$`bab` là một xâu con liên tiếp đối xứng có độ dài $3$. Xâu `aba` cũng là một đáp án hợp lệ.$e17_1$, 1
FROM problems p
WHERE p.title = 'Longest Palindromic Substring'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i17_2$cbbd$i17_2$, $o17_2$bb$o17_2$, $e17_2$Xâu con đối xứng dài nhất là `bb`, có độ dài $2$.$e17_2$, 2
FROM problems p
WHERE p.title = 'Longest Palindromic Substring'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i18_1$()[]{}$i18_1$, $o18_1$YES$o18_1$, $e18_1$Mỗi dấu ngoặc mở đều được đóng đúng loại và đúng thứ tự.$e18_1$, 1
FROM problems p
WHERE p.title = 'Valid Parentheses'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i18_2$([)]$i18_2$, $o18_2$NO$o18_2$, $e18_2$Dấu `]` đóng trước khi dấu `)` được đóng, nên thứ tự đóng ngoặc không hợp lệ.$e18_2$, 2
FROM problems p
WHERE p.title = 'Valid Parentheses'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i19_1$5 9
3 34 4 12 5$i19_1$, $o19_1$YES$o19_1$, $e19_1$Có thể chọn các phần tử $4$ và $5$, tổng bằng $9$.$e19_1$, 1
FROM problems p
WHERE p.title = 'Subset Sum'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i19_2$4 30
2 4 6 8$i19_2$, $o19_2$NO$o19_2$, $e19_2$Mọi tập con của mảng đều có tổng không thể bằng $30$.$e19_2$, 2
FROM problems p
WHERE p.title = 'Subset Sum'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i20_1$5$i20_1$, $o20_1$0 1 1 2 1 2$o20_1$, $e20_1$Các số từ $0$ đến $5$ có biểu diễn nhị phân lần lượt là $0,1,10,11,100,101$.$e20_1$, 1
FROM problems p
WHERE p.title = 'Counting Bits'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 1
  );

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT p.problem_id, $i20_2$2$i20_2$, $o20_2$0 1 1$o20_2$, $e20_2$Các số $0,1,2$ có số bit `1` lần lượt là $0,1,1$.$e20_2$, 2
FROM problems p
WHERE p.title = 'Counting Bits'
  AND NOT EXISTS (
    SELECT 1 FROM problem_examples pe
    WHERE pe.problem_id = p.problem_id AND pe.display_order = 2
  );

INSERT INTO problems (
  problem_id,
  title,
  description,
  constraints,
  difficulty,
  time_limit_ms,
  memory_limit_kb,
  allow_file_submit,
  is_public,
  created_by,
  created_at
) VALUES (
  1094,
  'Increasing Array',
  $md1094$# 1094 - Increasing Array

* **Time limit:** 1000 ms
* **Memory limit:** 524288 KB

You are given an array of $n$ integers. You want to modify the array so that it is increasing, i.e., every element is at least as large as the previous element.

On each move, you may increase the value of any element by one. What is the minimum number of moves required?

# Input

The first input line contains an integer $n$: the size of the array.

Then, the second line contains $n$ integers $x_1,x_2,\ldots,x_n$: the contents of the array.

# Output

Print the minimum number of moves.

# Example

Input:

```cpp
5
3 2 5 1 7
```

Output:

```cpp
5
```$md1094$,
  $c1094$* $1 \le n \le 2 \cdot 10^5$
* $1 \le x_i \le 10^9$$c1094$,
  'EASY',
  1000,
  524288,
  false,
  true,
  NULL,
  CURRENT_TIMESTAMP
)
ON CONFLICT (problem_id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  constraints = EXCLUDED.constraints,
  difficulty = EXCLUDED.difficulty,
  time_limit_ms = EXCLUDED.time_limit_ms,
  memory_limit_kb = EXCLUDED.memory_limit_kb,
  allow_file_submit = EXCLUDED.allow_file_submit,
  is_public = EXCLUDED.is_public,
  created_by = EXCLUDED.created_by;

INSERT INTO problem_examples (problem_id, input, output, explanation, display_order)
SELECT 1094, $i1094_1$5
3 2 5 1 7$i1094_1$, $o1094_1$5$o1094_1$, $e1094_1$Increase the second element from $2$ to $3$ and the fourth element from $1$ to $5$, using $1 + 4 = 5$ moves.$e1094_1$, 1
WHERE NOT EXISTS (
  SELECT 1 FROM problem_examples pe
  WHERE pe.problem_id = 1094 AND pe.display_order = 1
);

SELECT setval(pg_get_serial_sequence('problems', 'problem_id'), coalesce(max(problem_id), 1)) FROM problems;
SELECT setval(pg_get_serial_sequence('problem_examples', 'example_id'), coalesce(max(example_id), 1)) FROM problem_examples;
