CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    gender VARCHAR(10),
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    total_score INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    avatar_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP
);
-- tkhoan admin
INSERT INTO users (username, full_name, email, password_hash, gender, role, total_score, is_active) 
VALUES (
    'admin123', 
    'Chủ Trang Web', 
    'admin123@gmail.com', 
    '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW', 
    'female', 
    'ADMIN',
    0, 
    true
);

-- tkhoan user
INSERT INTO users (username, full_name, email, password_hash, gender, role, total_score, is_active) 
VALUES (
    'coder_01', 
    'Người Dùng Mẫu', 
    'user@example.com', 
    '$2a$12$XrTpI8KgCw7Si5rwdXLYYe8zbH5AETiZUXahya9mzfKWSb2rxDYNW', 
    'male', 
    'USER', -- Cột role mới thêm
    150, 
    true
);