server:
  port: ${JUDGE_PORT}

spring:
  data:
    redis:
      port: 6379
      host: redis
  application:
    name: judge
  output:
    ansi:
      enabled: always

judge:
  docker:
    host: unix:///var/run/docker.sock
    images:
      cpp: "oj-cpp:latest"
    dockerfiles:
      cpp: "${JUDGE_CPP_DOCKERFILE_PATH:./docker-env/cpp/}"

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
# logging:
#   level:
#     org:
#       springframework:
#         data:
#           redis: DEBUG
# debug: true
